version: '3.3'

services:
  app:
    build:
      context: api
    networks:
      - mynet
    restart: always
    volumes:
      - $PWD/api/app:/var/www/application/app
      - $PWD/api/bootstrap:/var/www/application/bootstrap
      - $PWD/api/routes:/var/www/application/routes
      - $PWD/api/database:/var/www/application/database
#      - $PWD/api/entry.sh:/opt/docker/bin/entrypoint.sh
      - app-log:/var/log/nginx/
    ports:
      - '1212:80'
#    entrypoint: ['php', 'artisan', 'migrate']

  db:
    image: bitnami/postgresql
    networks:
      - mynet
    restart: always
    environment:
      POSTGRESQL_DATABASE: "data"
      POSTGRESQL_USERNAME: "postgres"
      POSTGRESQL_PASSWORD: "postgres"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5499:5432'
    volumes:
      - my-db:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5480:80
# Names our volume
volumes:
  my-db:
  app-log:

networks:
  mynet:
